name: Validate

on:
    push: 
        branches: [plan]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
      
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch submodules (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          # terraform_version: ""
          terraform_wrapper: true

      - name: Setup Ansible
        run: pip install ansible

      - name: Terraform Validate
        id: terraform
        working-directory: ./deploy
        run: terraform validate -no-color

      - name: Ansible Validate
        id: ansible
        working-directory: ./config
        run: ansible-playbook deploy.yml --syntax-check